#!/usr/bin/env python
"""Correction terms of the double branched cover from Greene's spanning-tree model (arXiv:0805.1381).

For a connected diagram D with a marked point p on the strand `mark`, the Heegaard Floer complex of Sigma_2(K) is
generated by the Kauffman states x of D (matchings crossing -> corner of an unmarked region).  Greene's Theorem 4.1
gives the absolute grading
        gr(x) = delta(x) + (q(v_x) - 2m - 3 sigma(G_W)) / 4,
where G_W is the reduced Goeritz matrix of the white graph (g_ij = sum mu over the crossings joining w_i, w_j,
g_ii = - sum mu over the crossings at w_i), m its rank, q(v) = v^T G_W^{-1} v, delta(x) the number of crossings
with mu = -1 among those where x picks a white corner, and v_x the degree vector of the orientation of the white
graph in which the edge of a crossing c points to the white region on the same side of the overstrand as x(c).
The Spin^c structure of x is the class [v_x] in coker(G_W) (Section 4.5; det odd).  The incidence number mu(c)
is +1 when the black regions sit in the corners (a,b),(c,d) of the crossing [a,b,c,d] (Figure 2: over-strand
from bottom left to top right, shaded regions left and right) and -1 otherwise.

Theorem 6.8: the E_1 page is generated by the solitary states, those x for which the union of the matching
m_x (crossing -> x(c)) and m'_x (crossing -> the other region on the same side of the overstrand as x(c)) in
the incidence graph of regions and crossings has no cycle.  When every Spin^c class contains exactly one solitary
state, Sigma_2(K) is an L-space (Corollary 6.9) and d(Sigma_2(K), t) = gr(x_t).

    python greene_dinv.py 12n_491            # correction terms, both colourings and several marked strands
    python greene_dinv.py --validate         # alternating and Montesinos controls
"""
import ast, sys, os, itertools, math
from fractions import Fraction
import numpy as np, sympy
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'montesinos'))


# ---------------------------------------------------------------- diagram combinatorics
def faces_of(pd):
    """corner (i, j) = sector between labels pd[i][j] and pd[i][(j+1)%4]; returns (list of faces, corner -> face)."""
    pos = {}
    for i, q in enumerate(pd):
        for j, l in enumerate(q): pos.setdefault(l, []).append((i, j))
    corner_face, faces = {}, []
    for i in range(len(pd)):
        for j in range(4):
            if (i, j) in corner_face: continue
            f, cyc, ci, cj = len(faces), [], i, j
            while (ci, cj) not in corner_face:
                corner_face[(ci, cj)] = f; cyc.append((ci, cj))
                y = pd[ci][(cj + 1) % 4]
                oi, oj = [p for p in pos[y] if p != (ci, (cj + 1) % 4)][0]
                ci, cj = oi, oj
            faces.append(cyc)
    assert len(faces) == len(pd) + 2, 'not a connected planar diagram'
    return faces, corner_face


def colouring(pd, faces, corner_face):
    """checkerboard colouring: colour[face] in {0, 1}; corners j and j+2 of a crossing share a colour."""
    colour = {0: 0}; changed = True
    while changed:
        changed = False
        for i in range(len(pd)):
            fs = [corner_face[(i, j)] for j in range(4)]
            for j in range(4):
                if fs[j] in colour:
                    for k, same in ((j + 1, False), (j + 2, True), (j + 3, False)):
                        c = colour[fs[j]] if same else 1 - colour[fs[j]]
                        if fs[k % 4] not in colour: colour[fs[k % 4]] = c; changed = True
                        else: assert colour[fs[k % 4]] == c, 'inconsistent colouring'
    assert len(colour) == len(faces)
    return colour


class Diagram:
    def __init__(self, pd, black=0, mark=1):
        self.pd = [list(q) for q in pd]; n = len(pd); self.n = n
        self.faces, self.cf = faces_of(self.pd); col = colouring(self.pd, self.faces, self.cf)
        self.black = {f for f in col if col[f] == black}; self.white = {f for f in col if col[f] != black}
        # marked regions: the two faces along the strand `mark`
        marked = {self.cf[(i, j)] for i in range(n) for j in range(4) if mark in (self.pd[i][j], self.pd[i][(j + 1) % 4])}
        assert len(marked) == 2, marked
        self.rW = next(iter(marked & self.white)); self.rB = next(iter(marked & self.black))
        self.W = sorted(self.white - {self.rW}); self.widx = {w: k for k, w in enumerate(self.W)}; self.m = len(self.W)
        # incidence number and the white corners of every crossing
        self.mu, self.wcorners = [], []
        for i in range(n):
            fs = [self.cf[(i, j)] for j in range(4)]
            if fs[0] in self.black: self.mu.append(1); self.wcorners.append((1, 3))       # black at corners 0, 2
            else: self.mu.append(-1); self.wcorners.append((0, 2))
        # reduced Goeritz matrix of the white graph
        G = [[0] * self.m for _ in range(self.m)]
        for i in range(n):
            a, b = self.wcorners[i]; w1, w2 = self.cf[(i, a)], self.cf[(i, b)]
            if w1 == w2: continue                                               # nugatory loop: no contribution
            for w in (w1, w2):
                if w in self.widx: G[self.widx[w]][self.widx[w]] -= self.mu[i]
            if w1 in self.widx and w2 in self.widx:
                G[self.widx[w1]][self.widx[w2]] += self.mu[i]; G[self.widx[w2]][self.widx[w1]] += self.mu[i]
        self.G = sympy.Matrix(G); self.det = int(self.G.det()); self.D = abs(self.det)
        self.adj = self.G.adjugate(); ev = np.linalg.eigvalsh(np.array(G, dtype=float))
        assert all(abs(e) > 1e-9 for e in ev); self.sigma = int(sum(1 for e in ev if e > 0) - sum(1 for e in ev if e < 0))

    def side(self, j):
        """side of the over-strand (positions 1, 3) containing corner j: corners 3, 0 are on the side of end a"""
        return 0 if j in (0, 3) else 1

    def states(self):
        """Kauffman states: crossing i -> corner j, bijective onto the unmarked regions"""
        unmarked = [f for f in range(len(self.faces)) if f not in (self.rW, self.rB)]
        out, used = [], set()
        def rec(i, assign):
            if i == self.n:
                if len(used) == len(unmarked): out.append(list(assign))
                return
            for j in range(4):
                f = self.cf[(i, j)]
                if f in (self.rW, self.rB) or f in used: continue
                used.add(f); assign.append(j); rec(i + 1, assign); assign.pop(); used.discard(f)
        rec(0, []); return out

    def analyse(self, x):
        """grading, Spin^c label, delta, solitary flag of the state x (list of corner indices)"""
        v = [0] * self.m; delta = 0; edges = []
        for i, j in enumerate(x):
            a, b = self.wcorners[i]; w1, w2 = self.cf[(i, a)], self.cf[(i, b)]
            s = self.side(j); target = self.cf[(i, a)] if self.side(a) == s else self.cf[(i, b)]
            source = w2 if target == w1 else w1
            if w1 != w2:
                if target in self.widx: v[self.widx[target]] += 1
                if source in self.widx: v[self.widx[source]] -= 1
            if j in (a, b) and self.mu[i] == -1: delta += 1
            # m_x and m'_x edges in the incidence graph
            other = {0: 3, 3: 0, 1: 2, 2: 1}[j]
            edges.append(('c', i, self.cf[(i, j)])); edges.append(('c', i, self.cf[(i, other)]))
        vv = sympy.Matrix(v); q = Fraction(int((vv.T * self.adj * vv)[0]), self.det)
        gr = delta + (q - 2 * self.m - 3 * self.sigma) / 4
        lab = tuple(int(t) % self.D for t in (self.adj * vv))
        # solitary: no cycle in m_x U m'_x (union-find on crossings and regions)
        parent = {}
        def find(u):
            while parent.setdefault(u, u) != u: parent[u] = parent[parent[u]]; u = parent[u]
            return u
        solitary = True
        for _, i, f in edges:
            ru, rv = find(('c', i)), find(('f', f))
            if ru == rv: solitary = False; break
            parent[ru] = rv
        return {'gr': gr, 'q': q, 'delta': delta, 'v': tuple(v), 'label': lab, 'solitary': solitary}

    def spinc_index(self, labels):
        """index the classes [v] in coker(G_W) = Z/D by multiples of one generator; returns (index dict, lam)"""
        # generator: the class of a standard basis vector of order D
        for k in range(self.m):
            e = sympy.zeros(self.m, 1); e[k] = 1; lab = tuple(int(t) % self.D for t in (self.adj * e))
            order = next(o for o in range(1, self.D + 1) if all((o * t) % self.D == 0 for t in lab))
            if order == self.D:
                g = e; glab = lab; break
        else:
            return None, None
        index = {tuple((j * t) % self.D for t in glab): j for j in range(self.D)}
        lam = Fraction(int((g.T * self.adj * g)[0]), self.det) % 1
        return {l: index[l] for l in labels if l in index}, lam


def correction_terms(pd, black=0, mark=1, verbose=False):
    Dg = Diagram(pd, black, mark)
    X = [Dg.analyse(x) for x in Dg.states()]
    classes = {}
    for r in X: classes.setdefault(r['label'], []).append(r)
    idx, lam = Dg.spinc_index(list(classes))
    assert idx is not None and len(classes) == Dg.D, (len(classes), Dg.D)
    d, multi = {}, {}
    for lab, rs in classes.items():
        sol = [r for r in rs if r['solitary']]
        if len(sol) == 1: d[idx[lab]] = sol[0]['gr']
        else: multi[idx[lab]] = sorted(r['gr'] for r in sol)
    info = {'det': Dg.D, 'sigma_G': Dg.sigma, 'm': Dg.m, 'states': len(X), 'solitary': sum(r['solitary'] for r in X), 'lam': lam}
    if verbose: print(f'   black={black} mark={mark}: det {Dg.D}, {len(X)} states, {info["solitary"]} solitary, sigma(G_W)={Dg.sigma}, m={Dg.m}')
    return d, multi, lam, info


# ---------------------------------------------------------------- the surgery test (as in montesinos_u1.u1_admissible)
def u1_admissible(d, lam, D):
    from montesinos_u1 import lens_d
    dL = [lens_d(D, 2, i) for i in range(D)]; idx = [min(i // 2, (D + 1 - i) // 2) for i in range(D)]
    fits = []
    for eps in (1, -1):
        units = [a for a in range(D) if math.gcd(a, D) == 1 and (a * a * lam) % 1 == Fraction(eps * 2, D) % 1]
        dY = [eps * d[k] for k in range(D)]
        for a in units:
            for b in range(D):
                V, ok = {}, True
                for i in range(D):
                    w = dL[i] - dY[(a * i + b) % D]
                    if w < 0 or w.denominator != 1 or w.numerator % 2: ok = False; break
                    j = idx[i]; val = w.numerator // 2
                    if V.setdefault(j, val) != val: ok = False; break
                if not ok: continue
                seq = [V[j] for j in sorted(V)]
                if all(0 <= seq[j] - seq[j + 1] <= 1 for j in range(len(seq) - 1)): fits.append((eps, a, b, seq))
    return fits


def run(name, pd, marks=(1, 2, 3), verbose=True):
    results = {}
    for black in (0, 1):
        for mark in marks:
            try:
                d, multi, lam, info = correction_terms(pd, black, mark, verbose)
            except AssertionError as e:
                print('   black', black, 'mark', mark, 'failed:', e); continue
            results[(black, mark)] = (d, multi, lam, info)
            if multi: print(f'      classes with != 1 solitary state: {len(multi)} e.g. {list(multi.items())[:3]}')
    return results


if __name__ == '__main__':
    import database_knotinfo as dk
    rows = {r['name']: r for r in dk.link_list() if str(r.get('crossing_number', '')).strip().isdigit()}
    names = [a for a in sys.argv[1:] if not a.startswith('--')]
    for nm in names:
        pd = ast.literal_eval(rows[nm]['pd_notation']); print(nm, 'det', rows[nm]['determinant'], 'sigma', rows[nm]['signature'])
        res = run(nm, pd)
        full = {k: v for k, v in res.items() if not v[1]}
        for k, (d, multi, lam, info) in full.items():
            vals = sorted(d.values()); print(f'   {k}: d-invariants (sorted) {[str(x) for x in vals][:12]}... sum {sum(vals)} lam {lam}')
            if len(d) == info['det']:
                fits = u1_admissible(d, lam, info['det']); print('   u = 1 surgery test:', 'PASS ' + str(fits[:2]) if fits else 'OBSTRUCTED')
