"""Regression tests for exact Owens correction-term and parity computations.

Run from code/: python -m unittest discover -s tests -p test_owens.py -v
The independent full-box algorithm is used only for small forms here; no
archived result files are regenerated by these tests.
"""
from fractions import Fraction
from itertools import product
from pathlib import Path
import sys
import unittest
from unittest.mock import patch

import numpy as np

OWENS = Path(__file__).resolve().parents[1] / 'lower_bounds' / 'owens'
sys.path.insert(0, str(OWENS))

from owens_obstruction import (
    ClassMap, IncompleteCorrectionTerms, IsomorphismSearchLimit,
    adjugate_int, definite_goeritz_candidates, det_int, group_isos, m_Q,
    matching_exists, positive_definite,
    qtilde,
)
from crosscheck import m_and_labels
from linkform import compatible, linking_invariants
from traczyk import eps_and_dim3, jones_mod_t2t1, mirror_jones
import owens_u3
import owens_u4
import kinfo


class ExactCorrectionTerms(unittest.TestCase):
    def test_exact_ellipsoid_boundary(self):
        # The old float pruning admitted +/-1 at a radius just below 1/3.
        below = Fraction(1, 3) - Fraction(1, 10**20)
        values, _ = m_Q([[3]], need_all_classes=False, b0=below)
        self.assertEqual(values, {})
        values, _ = m_Q([[3]], need_all_classes=False, b0=Fraction(1, 3))
        self.assertEqual(set(values), {(1,), (2,)})
        self.assertEqual(set(values.values()), {Fraction(-1, 6)})

    def test_incomplete_search_is_explicit(self):
        with self.assertRaises(IncompleteCorrectionTerms):
            m_Q([[3]], b0=0, max_grow=1)
        # A zero initial radius now grows rather than remaining zero forever.
        self.assertEqual(len(m_Q([[3]], b0=0)[0]), 3)

    def test_invalid_forms_are_not_silently_reinterpreted(self):
        for form in ([[2]], [[-3]], [[1, 2], [0, 1]], [[1, 2]], [[Fraction(3, 2)]]):
            with self.subTest(form=form), self.assertRaises(ValueError):
                m_Q(form)

    def test_minima_agree_with_independent_full_box(self):
        forms = [np.array(Q, dtype=object) for Q in (
            [[3]], [[2, 1], [1, 2]], [[1, 3], [3, 12]],
            [[3, 2, 0], [2, 3, 0], [0, 0, 3]], qtilde(2, 2, 0),
        )]
        for Q in forms:
            with self.subTest(form=Q.tolist()):
                exact, cm = m_Q(Q)
                independent, determinant = m_and_labels(Q.tolist())
                adj = adjugate_int(Q)
                labels = {}
                ranges = [range(-int(Q[i, i]), int(Q[i, i]), 2) for i in range(len(Q))]
                for xi in product(*ranges):
                    label = tuple(sum(int(adj[i, j]) * xi[j] for j in range(len(Q)))
                                  % determinant for i in range(len(Q)))
                    labels[cm.coords(xi)] = label
                self.assertEqual(len(exact), determinant)
                self.assertEqual(exact, {g: independent[label] for g, label in labels.items()})

    def test_change_of_integral_basis_preserves_correction_terms(self):
        Q = np.diag([3, 5]).astype(object)
        P = np.array([[1, 2], [0, 1]], dtype=object)
        first, cm1 = m_Q(Q)
        second, cm2 = m_Q(P.T @ Q @ P)
        self.assertEqual(sorted(first.values()), sorted(second.values()))
        self.assertEqual(first[cm1.coords([0, 0])], second[cm2.coords([0, 0])])
        self.assertTrue(matching_exists(first, cm1, second, cm2))

    def test_positive_definiteness_uses_exact_arithmetic(self):
        n = 10**12
        self.assertTrue(positive_definite([[1, n], [n, n*n + 3]]))
        self.assertFalse(positive_definite([[1, n], [n, n*n - 3]]))

    def test_added_rank_four_goeritz_inputs_independently(self):
        # These are full d-invariant input checks, not full rank-four
        # obstruction reruns: candidate surgery-form searches take much longer.
        for name, determinant in (('13a_3712', 205), ('13a_3714', 273),
                                  ('13a_4212', 301), ('13a_4368', 269),
                                  ('13a_4830', 177), ('13a_4832', 213)):
            with self.subTest(knot=name):
                row = kinfo.rows()[name]
                spin_values = []
                for G in definite_goeritz_candidates(kinfo.pd_code(name)):
                    self.assertEqual(det_int(G), determinant)
                    exact, cm = m_Q(G)
                    independent, _ = m_and_labels(G.tolist())
                    self.assertEqual(sorted(exact.values()), sorted(independent.values()))
                    spin = exact[tuple(0 for _ in cm.d)]
                    self.assertEqual(spin, independent[tuple(0 for _ in G)])
                    spin_values.append(spin)
                self.assertIn(Fraction(-abs(int(row['signature'])), 4), spin_values)


class DiscriminantComparisons(unittest.TestCase):
    def test_primary_factors_and_quotient_coordinates(self):
        # Integral diagonalization need not already satisfy Smith divisibility.
        Q = np.diag([15, 9]).astype(object)
        cm = ClassMap(Q)
        self.assertEqual(cm.d, [3, 5, 9])
        self.assertEqual(cm.order, det_int(Q))
        for column in Q.T:
            self.assertEqual(cm.coords(column), tuple(0 for _ in cm.d))

    def test_matching_is_an_even_integer_inequality(self):
        cm = ClassMap([[1]])
        self.assertTrue(matching_exists({(): Fraction(2)}, cm, {(): Fraction(0)}, cm))
        for value in (Fraction(-2), Fraction(1), Fraction(1, 2)):
            self.assertFalse(matching_exists({(): value}, cm, {(): Fraction(0)}, cm))

    def test_partial_tables_and_search_caps_are_undecided(self):
        values, cm = m_Q([[3]])
        self.assertIsNone(matching_exists({}, cm, values, cm))
        with patch('owens_obstruction.group_isos', side_effect=IsomorphismSearchLimit('test')):
            self.assertIsNone(matching_exists(values, cm, values, cm))
        with self.assertRaises(IsomorphismSearchLimit):
            list(group_isos(cm, cm, cap=1))

    def test_different_groups_fail_before_searching(self):
        cyclic, cm1 = m_Q([[9]])
        noncyclic, cm2 = m_Q(np.diag([3, 3]))
        self.assertFalse(matching_exists(cyclic, cm1, noncyclic, cm2))

    def test_linking_filter_is_basis_invariant_and_distinguishes_sign(self):
        Q = np.diag([3, 5]).astype(object)
        P = np.array([[1, 2], [0, 1]], dtype=object)
        self.assertEqual(linking_invariants(Q), linking_invariants(P.T @ Q @ P))
        self.assertFalse(compatible(linking_invariants([[3]]), linking_invariants([[2, 1], [1, 2]])))
        inv = linking_invariants(np.diag([3, 3]))
        self.assertNotIn(3, inv)  # Deliberately no classification of this noncyclic part.


class SurgeryEnumeration(unittest.TestCase):
    def test_mod_two_lifts_are_complete_and_unimodular(self):
        for rank, lifts, expected in ((3, owens_u3.gl3f2_lifts(), 168),
                                      (4, list(owens_u4.gl4f2_lifts().values()), 20160)):
            self.assertEqual(len(lifts), expected)
            self.assertEqual(len({tuple((P % 2).flat) for P in lifts}), expected)
            self.assertTrue(all(abs(det_int(P)) == 1 for P in lifts))

    def test_small_reduced_form_lists_are_exact(self):
        # det 1 is small enough to independently enumerate a fixed full box.
        for rank, generator, diagonal_bound, product_bound in (
                (3, owens_u3.reduced_ternary_forms, 2, 2),
                (4, owens_u4.reduced_quaternary_forms, 4, 4)):
            expected = set()
            pairs = [(i, j) for i in range(rank) for j in range(i+1, rank)]
            for diagonal in product(range(1, diagonal_bound+1), repeat=rank):
                if tuple(sorted(diagonal)) != diagonal or np.prod(diagonal) > product_bound:
                    continue
                for entries in product(*(range(-(diagonal[i]//2), diagonal[i]//2+1) for i,j in pairs)):
                    Q = np.diag(diagonal).astype(object)
                    for (i,j), value in zip(pairs, entries):
                        Q[i,j] = Q[j,i] = value
                    if det_int(Q) == 1 and positive_definite(Q):
                        expected.add(tuple(Q.flat))
            self.assertEqual({tuple(Q.flat) for Q in generator(1)}, expected)

    def test_plumbing_schur_complement_and_even_diagonal_parameter(self):
        for rank, module in ((3, owens_u3), (4, owens_u4)):
            for n_even in (0, rank):
                determinant = 7 if rank == 3 and n_even == 3 else 1
                candidates = module.candidate_plumbings(determinant, n_even=n_even)
                self.assertTrue(candidates)
                for key, Q in candidates:
                    self.assertTrue(positive_definite(Q))
                    self.assertEqual(det_int(Q), determinant)
                    m = [int(Q[2*i, 2*i]) for i in range(rank)]
                    self.assertEqual(sum(value % 2 == 0 for value in m), n_even)
                    M = Q[::2, ::2]
                    reduced = 2*M - np.eye(rank, dtype=int)
                    self.assertEqual(det_int(reduced), det_int(Q))

    def test_sign_hypotheses_reject_uncovered_cases(self):
        self.assertEqual(owens_u3.obstruct_u3([], 4, 1)['verdict'], 'NOT_APPLICABLE')
        self.assertEqual(owens_u4.obstruct_u4([], 6, 1)['verdict'], 'NOT_APPLICABLE')


class JonesEvaluation(unittest.TestCase):
    def test_invalid_zero_evaluation_raises_instead_of_hanging(self):
        for polynomial in ({}, {2: 1, 1: -1, 0: 1}):
            with self.assertRaises(ValueError):
                eps_and_dim3(polynomial)

    def test_mirror_parity_and_laurent_evaluation(self):
        self.assertEqual(jones_mod_t2t1({-1: 1}), (1, -1))
        self.assertEqual(eps_and_dim3({0: -1, 1: 2}), (1, 1))
        self.assertEqual(eps_and_dim3(mirror_jones({0: -1, 1: 2})), (-1, 1))
        self.assertEqual(eps_and_dim3({0: -3}), (1, 2))


if __name__ == '__main__':
    unittest.main()
